import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";

import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const VALID_REGIONS = ["SPR", "SCPR", "NCPR", "NPR", "UNPR"] as const;

export async function GET(req: Request) {
  try {
    const session = await getSession();

    if (!session || session.role !== "MAIN_ADMIN") {
      return Response.json(
        { error: "Only Main Admin can generate exports." },
        { status: 403 }
      );
    }

    const { searchParams } = new URL(req.url);

    const month = String(searchParams.get("month") || "");
    const year = String(searchParams.get("year") || "");
    const region = String(searchParams.get("region") || "ALL");

    const parsedMonth = Number(month);
    const parsedYear = Number(year);

    if (!parsedMonth || parsedMonth < 1 || parsedMonth > 12) {
      return Response.json({ error: "Invalid month." }, { status: 400 });
    }

    if (!parsedYear || parsedYear < 2020 || parsedYear > 2100) {
      return Response.json({ error: "Invalid year." }, { status: 400 });
    }

    if (region !== "ALL" && !VALID_REGIONS.includes(region as any)) {
      return Response.json({ error: "Invalid region." }, { status: 400 });
    }

    const startDate = new Date(parsedYear, parsedMonth - 1, 1);
    const endDate = new Date(parsedYear, parsedMonth, 1);

    const where =
      region === "ALL"
        ? {
            date: {
              gte: startDate,
              lt: endDate,
            },
          }
        : {
            date: {
              gte: startDate,
              lt: endDate,
            },
            region: region as any,
          };

    const tasks = await prisma.task.findMany({
      where,
      orderBy: [{ date: "asc" }, { taskNumber: "asc" }],
      include: {
        sharedToOptions: {
          include: {
            sharedToOption: {
              select: {
                name: true,
              },
            },
          },
        },
        requestTypeOptions: {
          include: {
            requestTypeOption: {
              select: {
                name: true,
              },
            },
          },
        },
      },
    });

    const counts = {
      total: tasks.length,
      pending: tasks.filter((task) => task.status === "PENDING").length,
      inProgress: tasks.filter((task) => task.status === "IN_PROGRESS").length,
      completed: tasks.filter((task) => task.status === "COMPLETED").length,
      closed: tasks.filter((task) => task.status === "CLOSED").length,
    };

    const monthName = getMonthName(parsedMonth);
    const regionLabel = region === "ALL" ? "All Regions" : region;

    const doc = new Document({
      creator: "Regional Task Log",
      title: `Monthly Task Report - ${monthName} ${parsedYear}`,
      description: "Generated monthly task export",
      styles: {
        default: {
          document: {
            run: {
              font: "Arial",
              size: 22,
            },
            paragraph: {
              spacing: {
                after: 120,
              },
            },
          },
        },
      },
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: "REGIONAL TASK LOG",
                  bold: true,
                  size: 34,
                }),
              ],
            }),

            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: "Monthly Task Report",
                  bold: true,
                  size: 28,
                }),
              ],
            }),

            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: `${monthName} ${parsedYear} • ${regionLabel}`,
                  size: 22,
                }),
              ],
            }),

            spacer(),

            sectionHeading("Report Summary"),

            infoTable([
              ["Generated By", `${session.fullName} (${session.serviceNumber})`],
              ["Generated At", formatDateTime(new Date())],
              ["Month", `${monthName} ${parsedYear}`],
              ["Region", regionLabel],
              ["Total Tasks", String(counts.total)],
              ["Pending", String(counts.pending)],
              ["In Progress", String(counts.inProgress)],
              ["Completed", String(counts.completed)],
              ["Closed", String(counts.closed)],
            ]),

            spacer(),

            sectionHeading("Task Records"),

            ...(tasks.length === 0
              ? [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: "No task records found for the selected month and region.",
                        italics: true,
                      }),
                    ],
                  }),
                ]
              : tasks.flatMap((task, index) => {
                  const sharedTo = task.sharedToOptions
                    .map((item) => item.sharedToOption.name)
                    .join(", ");

                  const requestTypes = task.requestTypeOptions
                    .map((item) => item.requestTypeOption.name)
                    .join(", ");

                  return [
                    new Paragraph({
                      heading: HeadingLevel.HEADING_2,
                      children: [
                        new TextRun({
                          text: `${index + 1}. ${task.taskNumber}`,
                          bold: true,
                        }),
                      ],
                    }),

                    infoTable([
                      ["Date", formatDate(task.date)],
                      ["Region", task.region],
                      ["Atoll", task.atoll],
                      ["Island", task.island || "-"],
                      ["Status", formatStatus(task.status)],
                      ["Shared To", sharedTo || "-"],
                      ["Request Type", requestTypes || "-"],
                      [
                        "Information Date",
                        task.informationProvidedDate
                          ? formatDate(task.informationProvidedDate)
                          : "-",
                      ],
                      [
                        "Created By",
                        `${task.createdByName} (${task.createdByServiceNumber})`,
                      ],
                      ["Created At", formatDateTime(task.createdAt)],
                    ]),

                    labelParagraph("Task Details"),
                    bodyParagraph(task.description || "-"),

                    labelParagraph("Information Provided"),
                    bodyParagraph(task.informationProvided || "-"),

                    spacer(),
                  ];
                })),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    const safeRegion = region === "ALL" ? "ALL" : region;
    const fileName = `Task_Report_${safeRegion}_${parsedYear}_${String(
      parsedMonth
    ).padStart(2, "0")}.docx`;

    return new Response(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("TASK_WORD_EXPORT_ERROR", error);

    return Response.json(
      { error: "Could not generate task Word export." },
      { status: 500 }
    );
  }
}

function sectionHeading(text: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [
      new TextRun({
        text,
        bold: true,
        size: 26,
      }),
    ],
  });
}

function labelParagraph(text: string) {
  return new Paragraph({
    spacing: {
      before: 180,
      after: 80,
    },
    children: [
      new TextRun({
        text,
        bold: true,
        size: 22,
      }),
    ],
  });
}

function bodyParagraph(text: string) {
  return new Paragraph({
    spacing: {
      after: 160,
    },
    children: [
      new TextRun({
        text: cleanText(text),
        size: 22,
      }),
    ],
  });
}

function spacer() {
  return new Paragraph({
    children: [new TextRun({ text: "" })],
  });
}

function infoTable(rows: string[][]) {
  return new Table({
    width: {
      size: 100,
      type: WidthType.PERCENTAGE,
    },
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: {
                size: 30,
                type: WidthType.PERCENTAGE,
              },
              shading: {
                fill: "EAF2FF",
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: label,
                      bold: true,
                    }),
                  ],
                }),
              ],
            }),
            new TableCell({
              width: {
                size: 70,
                type: WidthType.PERCENTAGE,
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: cleanText(value),
                    }),
                  ],
                }),
              ],
            }),
          ],
        })
    ),
  });
}

function tableBorders() {
  return {
    top: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    left: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    right: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
  };
}

function cleanText(value: string) {
  return String(value || "-").replace(/\r\n/g, "\n").trim() || "-";
}

function getMonthName(month: number) {
  return new Intl.DateTimeFormat("en-GB", {
    month: "long",
  }).format(new Date(2026, month - 1, 1));
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(date);
}

function formatDateTime(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}

function formatStatus(status: string) {
  if (status === "PENDING") return "Pending";
  if (status === "IN_PROGRESS") return "In Progress";
  if (status === "COMPLETED") return "Completed";
  if (status === "CLOSED") return "Closed";
  return status;
}