import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";

import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const VALID_REGIONS = ["SPR", "SCPR", "NCPR", "NPR", "UNPR"] as const;

export async function GET(req: Request) {
  try {
    const session = await getSession();

    if (!session || session.role !== "MAIN_ADMIN") {
      return Response.json(
        { error: "Only Main Admin can generate exports." },
        { status: 403 }
      );
    }

    const { searchParams } = new URL(req.url);

    const month = String(searchParams.get("month") || "");
    const year = String(searchParams.get("year") || "");
    const region = String(searchParams.get("region") || "ALL");

    const parsedMonth = Number(month);
    const parsedYear = Number(year);

    if (!parsedMonth || parsedMonth < 1 || parsedMonth > 12) {
      return Response.json({ error: "Invalid month." }, { status: 400 });
    }

    if (!parsedYear || parsedYear < 2020 || parsedYear > 2100) {
      return Response.json({ error: "Invalid year." }, { status: 400 });
    }

    if (region !== "ALL" && !VALID_REGIONS.includes(region as any)) {
      return Response.json({ error: "Invalid region." }, { status: 400 });
    }

    const startDate = new Date(parsedYear, parsedMonth - 1, 1);
    const endDate = new Date(parsedYear, parsedMonth, 1);

    const where =
      region === "ALL"
        ? {
            date: {
              gte: startDate,
              lt: endDate,
            },
          }
        : {
            date: {
              gte: startDate,
              lt: endDate,
            },
            region: region as any,
          };

    const records = await prisma.yaumiyyaRecord.findMany({
      where,
      orderBy: [{ date: "asc" }, { createdAt: "asc" }],
      include: {
        participants: {
          orderBy: {
            displayName: "asc",
          },
        },
        assignedTaskItems: {
          orderBy: {
            createdAt: "asc",
          },
        },
      },
    });

    const totalParticipants = records.reduce(
      (sum, record) => sum + record.participants.length,
      0
    );

    const totalAssignedTasks = records.reduce(
      (sum, record) => sum + record.assignedTaskItems.length,
      0
    );

    const completedAssignedTasks = records.reduce(
      (sum, record) =>
        sum +
        record.assignedTaskItems.filter((task) => task.isCompleted).length,
      0
    );

    const monthName = getMonthName(parsedMonth);
    const regionLabel = region === "ALL" ? "All Regions" : region;

    const doc = new Document({
      creator: "Regional Task Log",
      title: `Monthly Yaumiyya Report - ${monthName} ${parsedYear}`,
      description: "Generated monthly Yaumiyya export",
      styles: {
        default: {
          document: {
            run: {
              font: "Arial",
              size: 22,
            },
            paragraph: {
              spacing: {
                after: 120,
              },
            },
          },
        },
      },
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: "REGIONAL TASK LOG",
                  bold: true,
                  size: 34,
                }),
              ],
            }),

            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: "Monthly Yaumiyya Report",
                  bold: true,
                  size: 28,
                }),
              ],
            }),

            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: `${monthName} ${parsedYear} • ${regionLabel}`,
                  size: 22,
                }),
              ],
            }),

            spacer(),

            sectionHeading("Report Summary"),

            infoTable([
              ["Generated By", `${session.fullName} (${session.serviceNumber})`],
              ["Generated At", formatDateTime(new Date())],
              ["Month", `${monthName} ${parsedYear}`],
              ["Region", regionLabel],
              ["Total Yaumiyya Records", String(records.length)],
              ["Total Participants", String(totalParticipants)],
              ["Total Assigned Tasks", String(totalAssignedTasks)],
              ["Completed Assigned Tasks", String(completedAssignedTasks)],
              [
                "Pending Assigned Tasks",
                String(totalAssignedTasks - completedAssignedTasks),
              ],
            ]),

            spacer(),

            sectionHeading("Yaumiyya Records"),

            ...(records.length === 0
              ? [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: "No Yaumiyya records found for the selected month and region.",
                        italics: true,
                      }),
                    ],
                  }),
                ]
              : records.flatMap((record, index) => {
                  const participants = record.participants
                    .map((participant) => {
                      const serviceNo = participant.serviceNo
                        ? ` (${participant.serviceNo})`
                        : "";
                      return `${participant.displayName}${serviceNo}`;
                    })
                    .join(", ");

                  const completed = record.assignedTaskItems.filter(
                    (task) => task.isCompleted
                  ).length;

                  return [
                    new Paragraph({
                      heading: HeadingLevel.HEADING_2,
                      children: [
                        new TextRun({
                          text: `${index + 1}. ${
                            record.meetingTitle || "Yaumiyya Meeting Note"
                          }`,
                          bold: true,
                        }),
                      ],
                    }),

                    infoTable([
                      ["Date", formatDate(record.date)],
                      ["Start Time", record.startTime || "-"],
                      ["Finished Time", record.finishedTime || "-"],
                      ["Region", record.region],
                      ["Participants Count", String(record.participants.length)],
                      ["Assigned Tasks", String(record.assignedTaskItems.length)],
                      ["Completed", String(completed)],
                      [
                        "Pending",
                        String(record.assignedTaskItems.length - completed),
                      ],
                      [
                        "Created By",
                        `${record.createdByName} (${record.createdByServiceNumber})`,
                      ],
                      ["Created At", formatDateTime(record.createdAt)],
                    ]),

                    labelParagraph("Participants"),
                    bodyParagraph(participants || "-"),

                    labelParagraph("Meeting Notes"),
                    bodyParagraph(record.meetingNotes || "-"),

                    labelParagraph("Assigned Tasks"),

                    ...(record.assignedTaskItems.length === 0
                      ? [bodyParagraph(record.assignedTasks || "-")]
                      : record.assignedTaskItems.flatMap((task, taskIndex) => [
                          new Paragraph({
                            children: [
                              new TextRun({
                                text: `${taskIndex + 1}. ${
                                  task.assignedToName
                                }${
                                  task.assignedToServiceNo
                                    ? ` (${task.assignedToServiceNo})`
                                    : ""
                                } — ${
                                  task.isCompleted ? "Completed" : "Pending"
                                }`,
                                bold: true,
                              }),
                            ],
                          }),
                          bodyParagraph(task.taskDetails || "-"),
                        ])),

                    spacer(),
                  ];
                })),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    const safeRegion = region === "ALL" ? "ALL" : region;
    const fileName = `Yaumiyya_Report_${safeRegion}_${parsedYear}_${String(
      parsedMonth
    ).padStart(2, "0")}.docx`;

    return new Response(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("YAUMIYYA_WORD_EXPORT_ERROR", error);

    return Response.json(
      { error: "Could not generate Yaumiyya Word export." },
      { status: 500 }
    );
  }
}

function sectionHeading(text: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [
      new TextRun({
        text,
        bold: true,
        size: 26,
      }),
    ],
  });
}

function labelParagraph(text: string) {
  return new Paragraph({
    spacing: {
      before: 180,
      after: 80,
    },
    children: [
      new TextRun({
        text,
        bold: true,
        size: 22,
      }),
    ],
  });
}

function bodyParagraph(text: string) {
  return new Paragraph({
    spacing: {
      after: 160,
    },
    children: [
      new TextRun({
        text: cleanText(text),
        size: 22,
      }),
    ],
  });
}

function spacer() {
  return new Paragraph({
    children: [new TextRun({ text: "" })],
  });
}

function infoTable(rows: string[][]) {
  return new Table({
    width: {
      size: 100,
      type: WidthType.PERCENTAGE,
    },
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: {
                size: 30,
                type: WidthType.PERCENTAGE,
              },
              shading: {
                fill: "EAF2FF",
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: label,
                      bold: true,
                    }),
                  ],
                }),
              ],
            }),
            new TableCell({
              width: {
                size: 70,
                type: WidthType.PERCENTAGE,
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: cleanText(value),
                    }),
                  ],
                }),
              ],
            }),
          ],
        })
    ),
  });
}

function tableBorders() {
  return {
    top: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    left: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
    right: { style: BorderStyle.SINGLE, size: 1, color: "D7E6FF" },
  };
}

function cleanText(value: string) {
  return String(value || "-").replace(/\r\n/g, "\n").trim() || "-";
}

function getMonthName(month: number) {
  return new Intl.DateTimeFormat("en-GB", {
    month: "long",
  }).format(new Date(2026, month - 1, 1));
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(date);
}

function formatDateTime(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}